// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker/executor.go
//
// Generated by this command:
//
//	mockgen -source=internal/worker/executor.go -destination=internal/worker/mocks/worker_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	models "github.com/ayushsarode/distributed-job-scheduler/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRunner is a mock of JobRunner interface.
type MockJobRunner struct {
	ctrl     *gomock.Controller
	recorder *MockJobRunnerMockRecorder
	isgomock struct{}
}

// MockJobRunnerMockRecorder is the mock recorder for MockJobRunner.
type MockJobRunnerMockRecorder struct {
	mock *MockJobRunner
}

// NewMockJobRunner creates a new mock instance.
func NewMockJobRunner(ctrl *gomock.Controller) *MockJobRunner {
	mock := &MockJobRunner{ctrl: ctrl}
	mock.recorder = &MockJobRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRunner) EXPECT() *MockJobRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockJobRunner) Run(ctx context.Context, payload json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockJobRunnerMockRecorder) Run(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockJobRunner)(nil).Run), ctx, payload)
}

// MockResultReporter is a mock of ResultReporter interface.
type MockResultReporter struct {
	ctrl     *gomock.Controller
	recorder *MockResultReporterMockRecorder
	isgomock struct{}
}

// MockResultReporterMockRecorder is the mock recorder for MockResultReporter.
type MockResultReporterMockRecorder struct {
	mock *MockResultReporter
}

// NewMockResultReporter creates a new mock instance.
func NewMockResultReporter(ctrl *gomock.Controller) *MockResultReporter {
	mock := &MockResultReporter{ctrl: ctrl}
	mock.recorder = &MockResultReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultReporter) EXPECT() *MockResultReporterMockRecorder {
	return m.recorder
}

// ReportResult mocks base method.
func (m *MockResultReporter) ReportResult(ctx context.Context, job *models.Job, success bool, errMsg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportResult", ctx, job, success, errMsg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportResult indicates an expected call of ReportResult.
func (mr *MockResultReporterMockRecorder) ReportResult(ctx, job, success, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportResult", reflect.TypeOf((*MockResultReporter)(nil).ReportResult), ctx, job, success, errMsg)
}
