install-deps:
	bash scripts/install-deps.sh 

build: 
	bash scripts/build.sh 

run:
	go run main.go 

clean:
	bash scripts/clean.sh 

lint:
	bash scripts/lint.sh

unit-tests:
	bash scripts/unit-tests.sh

integration-tests:
	bash scripts/integration-tests.sh

